### PR TITLE
Auto saving the config on exiting, changing the to config file

### PR DESCRIPTION
**Pull request by Maschell**
- Only save the IP-Address (the end-user shouldn't worry about any of
the other values) + they should be final anyway?!?! 
-change the config path to a local path. Is there any reason to put it in that specific path? 

I like the idea of saving stuff to a config (wanted to do it anyway), but I wouldn't save all values into it. These are final paramerters and shouldn't change at all. If someone really wants to tweak it, he/she has to look at the code anyway. Then he/she can also change the value in the Settings.java itself. I have the feeling that giving the user the power to change them, it wouldn't end good.

What do you think about it?

### CODE REVIEW

**Comment by QuarkTheAwesome** [comment]
While I agree that the user doesn't need access to *all* of the values, I think that some things like the polling intervals have enough edge cases to warrant having them accessible. I may have a terrible connection, or want to minimize input delay on the controllers, or whatever. I don't really see a reason *not* to provide these in a config, even if the majority of users never touch it (most wouldn't touch it anyway, thanks to your auto-saving!)
I'm still happy to merge as-is; I just think a bit more fine-grained control for those willing to tweak the config wouldn't go amiss.

**Comment by Maschell** [comment]
Maybe one of the parameter the user could change would be "PROCESS_CMD_INTERVAL" (aka how often data is send to the app) (+maybe number of retries after a connection loss. All other value should be pretty much fixed.

**Comment by QuarkTheAwesome** [comment]
Wasn't there a separate value for polling the controllers? Wouldn't be much point in changing PROCESS_CMD_INTERVAL if you couldn't change that either.

**Comment by Maschell** [comment]
There is one for polling the data and one for sending the data

**Pull request merged**
